server:
  port: 4001
  servlet:
    session:
      tracking-modes: cookie

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/plagiarism
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 20